theme = "base16_transparent"

[editor]
# Use system clipboard for yank/paste/delete operations
clipboard-provider = "wayland"

line-number = "relative"
mouse = true
end-of-line-diagnostics = "disable"

[editor.lsp]
display-messages = false
display-inlay-hints = true
enable = true

[editor.gutters]
line-numbers = { min-width = 1 }

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "error"

[editor.soft-wrap]
enable = true

[keys.normal]
"A-f" = "select_all"  # Alt+f to select all text
esc = [ "normal_mode", ":format" , ":write!" ] # For quick saving
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
Z = ":toggle gutters.line-numbers.min-width 170 3"
g = { v = ["vsplit", "jump_view_down", "goto_definition", "collapse_selection"], V = ["hsplit", "jump_view_down", "goto_definition", "collapse_selection"] }
"A-s" = "vsplit"  # Alt+s for vertical split


[keys.normal.space]
H = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/serpl-replace.sh"

# LSP actions
l = { l = "goto_definition", r = "rename_symbol", h = "hover", f = "format_selections", a = "code_action" }


[keys.normal.space.q]
q = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh open" # Open the file(s) in the current window
v = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh vsplit" # Open the file(s) in a horizontal pane
s = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh hsplit" # Open the file(s) in a vertical pane

[keys.select]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "collapse_selection"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after", "collapse_selection"]
